version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wsj1989
      PGDATA: /home/pgdata
    ports:
      - 8081:5432
    volumes:
      - ./pgdata:/home/pgdata

  server:
    build: ./server
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      # MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 8080:5000
    volumes:
      - ./server_data:/home/server/data
    depends_on:
      - db