version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wsj1989
      PGDATA: /home/pgdata
    ports:
      - 21211:5432
    volumes:
      - ./pgdata:/home/pgdata

  server:
    build: ./server
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432 # 这个是上边db的端口
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 21210:5000
    volumes:
      - ./server_data:/home/server/data
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jessewee@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: 1989
    ports:
      - 21212:80
    volumes:
     # 启动前需要确保路径能被pgadmin访问，pgadmin的用户id和用户组id是5050:5050
     # sudo chown -R 5050:5050 pgadmin_data
     - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  chat:
    build: ./chat
    restart: always
    ports:
      - 21213:8765
    volumes:
      - ./chat_data:/home/chat/data